packaging_format = 2

id = "cf_custom"
name = "CF Customizations"
description.en = "Install CF Customizations"
description.fr = "Installe les personnalisations CF"

version = "2.6~ynh1"

maintainers = ["pbrisacier@mncc.fr"]

[upstream]
# NB: Only the "license" key is mandatory. Remove entries for which there's no relevant data
license = "free"

[integration]
yunohost = ">= 11.1.21"
architectures = "all"
multi_instance = false
ldap = "not_relevant"
sso = "not_relevant"
disk = "1M"
ram.build = "1M"
ram.runtime = "1M"

[install]
    [install.catalog]
    type = "select"
    choices = ["Default", "ComputableFacts"]

    [install.theme]
    type = "select"
    choices = ["Default", "ComputableFacts", "Add-Apps"]

[resources]
    # See the packaging documentation for the full set
    # of explanation regarding the behavior and properties for each of those

    [resources.permissions]
    # We need to keep this section otherwise the app admin page is not displayed

    [resources.apt]
    # This will automatically install/uninstall the following apt packages
    # and implicitly define the $phpversion setting as 8.0 (if phpX.Y-foobar dependencies are listed)
    packages = ["tmux"]
