#!/bin/bash
# In simple cases, you don't need a config script. 

# With a simple config_panel.toml, you can write in the app settings, in the 
# upstream config file or replace complete files (logo ...) and restart services.

# The config scripts allows you to go further, to handle specific cases 
# (validation of several interdependent fields, specific getter/setter for a value,
# display dynamic informations or choices, pre-loading of config type .cube... ).

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS
#=================================================

#=================================================
# SPECIFIC GETTERS FOR TOML SHORT KEY
#=================================================

#=================================================
# SPECIFIC VALIDATORS FOR TOML SHORT KEYS
#=================================================

#=================================================
# SPECIFIC SETTERS FOR TOML SHORT KEYS
#=================================================
set__catalog() {
    ynh_add_config --template="apps_catalog.$catalog.yml" --destination="/etc/yunohost/apps_catalog.yml"
    chown root:root "/etc/yunohost/apps_catalog.yml"
    rm -f /var/cache/yunohost/repo/default.json

    ynh_app_setting_set $app catalog $catalog
}

#=================================================
# GENERIC FINALIZATION
#=================================================
ynh_app_config_run $1
