#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

# Settings are automatically loaded as bash variables
# in every app script context, therefore typically these will exist:
# - $domain
# - $path
# - $language
# - $install_dir
# - $port
# ...

# For remove operations :
# - the core will deprovision every resource defined in the manifest **after** this script is ran
# this includes removing the install directory, and data directory (if --purge was used)

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
# REMOVE SYSTEMD SERVICE 
#=================================================

# Back to default catalog
ynh_add_config --template="apps_catalog.Default.yml" --destination="/etc/yunohost/apps_catalog.yml"
chown root:root "/etc/yunohost/apps_catalog.yml"
rm -f /var/cache/yunohost/repo/default.json

# Remove Admin theme
rm /usr/share/yunohost/admin/override.css
rm /usr/share/yunohost/admin/override.js
rm /usr/share/yunohost/admin/logo.png
rm /usr/share/yunohost/admin/index.html
mv "/usr/share/yunohost/admin/index.html.save" "/usr/share/yunohost/admin/index.html"

# Remove Portal theme
rm -Rf "/usr/share/ssowat/portal/assets/themes/Add-Apps/"
rm -Rf "/usr/share/ssowat/portal/assets/themes/ComputableFacts/"
# TODO: change back to default theme only if current theme in (Add-Apps, ComputableFacts)
yunohost settings set misc.portal.portal_theme --value default

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last
